version: '3'
services:
  nos_gestes_climat_qc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./nosgestesclimat:/nosgestesclimat
      - ./nosgestesclimat-site:/nosgestesclimat-site
    container_name: nos_gestes_climat_qc
